version: '3'
services:
  web:
    #container_name: manufacture-web
    build: .
    command: sh entrypoint.sh
    tty: true
    volumes:
    - .:/home/project
    depends_on:
    - db
    networks:
     manufacture:
      aliases:
      - web
  nginx:
    image: nginx
    #container_name: manufacture-nginx
    volumes:
    - ./nginx/data:/usr/share/nginx/html
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/config/mime.types:/etc/nginx/mime.types
    - ./nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/logs:/var/log/nginx/
    - ./nginx/nginx/ssl:/ssl/
    - ./collect_static:/var/nginx/static/
    - ./files:/var/nginx/media/
    depends_on:
    - web
    networks:
    - manufacture
    environment:
    - SERVER_NAME=disk.tcce.pro
    ports:
    - "9000:80"
    - "9443:443"
  db:
    image: postgres
    restart: always
    #container_name: manufacture-db
    networks:
     manufacture:
      aliases:
       - db
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=mcmc1918
    - POSTGRES_USER=mcmc
    - POSTGRES_DB=manufacture
    # the ports is for test, can be closed
    ports:
    - "9432:5432"

networks:
  manufacture: