# Generated by Django 2.0.8 on 2020-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MF_TZ',
            fields=[
                ('TZ_NO', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='通知单号')),
                ('MO_NO', models.CharField(blank=True, max_length=20, null=True, verbose_name='制定单号')),
            ],
            options={
                'verbose_name': '通知单',
                'verbose_name_plural': '通知单',
                'db_table': 'MF_TZ',
            },
        ),
        migrations.AlterField(
            model_name='mf_mo',
            name='MO_NO',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='制定单号'),
        ),
        migrations.AlterField(
            model_name='mf_mo',
            name='SO_NO',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='受订单号'),
        ),
    ]
