# Generated by Django 2.1.5 on 2020-03-22 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_order_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='受订单')),
                ('sell_order', models.IntegerField(blank=True, null=True, verbose_name='受订单ID')),
                ('manufacture_order_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='制订单')),
                ('manufacture_order', models.IntegerField(blank=True, null=True, verbose_name='制订单ID')),
                ('part_no_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='图号')),
                ('part_no', models.IntegerField(blank=True, null=True, verbose_name='图号ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '制订单流程',
                'verbose_name_plural': '制订单流程',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='工序')),
                ('part_no_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='图号')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Department', verbose_name='部门')),
                ('mop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.Mop', verbose_name='制订单流程')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.Procedure', verbose_name='上一个工序')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='交接数量')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Department', verbose_name='部门')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.Procedure', verbose_name='工序')),
            ],
            options={
                'verbose_name': '交接单',
                'verbose_name_plural': '交接单',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='名称')),
                ('sub_procedure', models.CharField(blank=True, max_length=32, null=True, verbose_name='子工序')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='完成数量')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='总数量')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('stop_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.Procedure', verbose_name='工序')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='检验人员')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
