# Generated by Django 2.0.8 on 2020-03-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_procedure_mop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工序'),
        ),
        migrations.AddField(
            model_name='task',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工序'),
        ),
    ]
