# Generated by Django 2.0.8 on 2020-03-24 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0003_auto_20200324_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='procedure_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total',
        ),
        migrations.AddField(
            model_name='receipt',
            name='deliver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver', to=settings.AUTH_USER_MODEL, verbose_name='发单人员'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deliver_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发单时间'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deliver_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_procedure', to='procedure.Procedure', verbose_name='发送工序'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deliver_procedure_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发送工序'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='签单人员'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签单时间'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_procedure', to='procedure.Procedure', verbose_name='接收工序'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_procedure_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='接收工序'),
        ),
    ]
