# Generated by Django 2.0.8 on 2020-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_auto_20200324_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '已发送'), (2, '已接收')], default=0, verbose_name='状态'),
        ),
    ]
