# Generated by Django 2.0.8 on 2020-03-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0005_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
