# Generated by Django 2.0.8 on 2020-03-24 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_receipt_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total',
        ),
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
    ]
