# Generated by Django 2.0.8 on 2020-03-24 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0007_auto_20200324_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='deliver_at',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receiver_at',
            new_name='received_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_at',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='stop_at',
            new_name='stopped_at',
        ),
        migrations.AddField(
            model_name='procedure',
            name='delivered_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='发出数量'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='received_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='接收数量'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deliver_type',
            field=models.IntegerField(choices=[(0, '正常'), (0, '反工')], default=0, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mop',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='完成数量'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='create_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
