# Generated by Django 2.1.5 on 2020-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0008_auto_20200324_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='remake_quantity',
            field=models.IntegerField(default=0, verbose_name='返工数量'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='delivered_quantity',
            field=models.IntegerField(default=0, verbose_name='发出数量'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='完成数量'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='received_quantity',
            field=models.IntegerField(default=0, verbose_name='接收数量'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='deliver_type',
            field=models.IntegerField(choices=[(0, '未定义'), (1, '正常'), (2, '反工')], default=0, verbose_name='类型'),
        ),
    ]
