# Generated by Django 2.1.5 on 2020-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0009_auto_20200328_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='完成数量'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.FloatField(default=1, verbose_name='权重'),
        ),
    ]
