# Generated by Django 2.1.5 on 2020-03-28 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0010_auto_20200328_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plan_quantity',
            field=models.IntegerField(default=0, verbose_name='计划完成数量'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 23, 35, 49, 479790), null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='实际完成数量'),
        ),
    ]
