# Generated by Django 2.0.8 on 2020-03-30 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0011_auto_20200328_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 30, 16, 30, 18, 840958), null=True, verbose_name='创建时间'),
        ),
    ]
