# Generated by Django 2.1.5 on 2020-04-05 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0012_auto_20200330_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 5, 11, 48, 32, 530995), null=True, verbose_name='创建时间'),
        ),
    ]
