# Generated by Django 2.1.5 on 2020-04-11 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0013_auto_20200405_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 11, 23, 48, 34, 62464), null=True, verbose_name='创建时间'),
        ),
    ]
