# Generated by Django 2.0.8 on 2020-04-09 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0014_auto_20200409_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 10, 24, 39, 749751), null=True, verbose_name='创建时间'),
        ),
    ]
