# Generated by Django 2.1.5 on 2020-05-16 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0015_auto_20200411_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='交接数量')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='签单人员')),
                ('receiver_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.Procedure', verbose_name='接收工序')),
            ],
            options={
                'verbose_name': '接收历史',
                'verbose_name_plural': '接收历史',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 21, 10, 51, 213173), null=True, verbose_name='创建时间'),
        ),
    ]
