# Generated by Django 2.0.8 on 2020-04-09 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0015_auto_20200409_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 10, 33, 45, 858966), null=True, verbose_name='创建时间'),
        ),
    ]
