# Generated by Django 2.1.5 on 2020-05-16 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0016_auto_20200516_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivehistory',
            name='received_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 13, 18, 52, 699569, tzinfo=utc), null=True, verbose_name='接收时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 21, 18, 52, 700565), null=True, verbose_name='创建时间'),
        ),
    ]
