# Generated by Django 2.1.5 on 2020-05-16 13:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_auto_20200516_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivehistory',
            name='received_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='接收时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 21, 21, 53, 44022), null=True, verbose_name='创建时间'),
        ),
    ]
