# Generated by Django 2.0.8 on 2020-03-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user', '0004_auto_20200317_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='权限组'),
        ),
    ]
