# Generated by Django 2.0.8 on 2020-03-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='groups',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='user.Department', verbose_name='上级部门'),
        ),
    ]
