# Generated by Django 2.0.8 on 2020-03-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200317_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='groups',
            new_name='admins',
        ),
    ]
