# Generated by Django 2.1.5 on 2020-04-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('app_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('terminal_type', models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'ANDROID'), (2, 'IOS')], default=0, verbose_name='终端类型')),
                ('release_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '版本管理',
                'verbose_name_plural': '版本管理',
            },
        ),
    ]
