from enum import Enum

# 交接单状态
RECEIPT_STATUS_UN_KNOW = 0
RECEIPT_STATUS_DELIVERED = 1
RECEIPT_STATUS_RECEIVED = 2

# 交接单类型
RECEIPT_TYPE_UN_DEFINE = 0
RECEIPT_TYPE_NORMAL = 1
RECEIPT_TYPE_REMAKE = 2

