from enum import Enum

# 工序状态
PROCEDURE_STATUS_UN_START = 0  # 未开始
PROCEDURE_STATUS_UNDER_GOING = 1  # 进行中
PROCEDURE_STATUS_FINISHED = 2  # 已完成

# 交接单状态
RECEIPT_STATUS_UN_KNOW = 0
RECEIPT_STATUS_DELIVERED = 1
RECEIPT_STATUS_RECEIVED = 2

# 交接单类型
RECEIPT_TYPE_UN_DEFINE = 0
RECEIPT_TYPE_NORMAL = 1
RECEIPT_TYPE_REMAKE = 2

# 任务状态
TASK_STATUS_UN_START = 0  # 未开始
TASK_STATUS_UNDER_GOING = 1  # 进行中
TASK_STATUS_FINISHED = 2  # 已完成
